from GoGame import GoGame
go = GoGame(5)
go.takeTurn((2,1),2)
print(go.countScore())
go.takeTurn((0,0),2)
go.takeTurn((0,1),2)
go.takeTurn((1,1),1)
print(go.countScore())
go.takeTurn((3,1),1)
go.takeTurn((2,0),1)
print(go.countScore())
go.takeTurn((2,2),1)
go.takeTurn((2,3),1)
go.takeTurn((2,4),1)
go.printBoard()
print(go.countScore())