from GoGame import GoGame
go = GoGame(5)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)
go.takeTurn(go.getRandomMove(2),2)
go.takeTurn(go.getRandomMove(1),1)

go.printBoard()
print(go.countScore())